# Assignment 3

## Task 1

#### Problem 1

In [1]:
def test():
    try:
        return 5/0
    except:
        print("Error: Dividing by 0")
test()

Error: Dividing by 0


#### Problem 2

In [2]:
subjects=["Americans","Indians"] 
verbs=["play","watch"] 
objects=["Baseball","Cricket"]

result = [x+" "+y+" "+z for x in subjects for y in verbs for z in objects]
for i in result:
    print(i)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


## Task 2

####  Problem 1

In [4]:
import numpy as np
x = np.array([int(i) for i in input("Enter the numbers without any delimiters: ")])
y = np.vander(x)
print(y)

Enter the numbers without any delimiters: 2345
[[  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]
